USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_EXAMENSARBETE
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for examensarbete_data_engineer';

