USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS FLIGHT_EMISSIONS;

CREATE SCHEMA IF NOT EXISTS FLIGHT_EMISSIONS.STAGING;
CREATE SCHEMA IF NOT EXISTS FLIGHT_EMISSIONS.WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS FLIGHT_EMISSIONS.MARTS;